<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Tidverk.TaxTableImporter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tidverk.Infrastructure/Tidverk.Infrastructure.csproj" />
  </ItemGroup>
</Project>
