<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tidverk.Infrastructure/Tidverk.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../src/Tidverk.Infrastructure/Tax/Data/tax-2026.json" Link="Tax/Data/tax-2026.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
